<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Timeline Portfolio | Tutorialzine Demo</title>
        
        <!-- Our Stylesheet -->
        <!--<link rel="stylesheet" href="assets/css/timeline.css" />-->
        <!--<link rel="stylesheet" href="assets/css/styles.css" />-->
        <!--<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Dancing+Script|Antic+Slab" />-->
		
		<link rel="stylesheet" href="/assets/opt/css/styles.css" />
        
        <!--[if lt IE 9]>
          <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    
    <body>

<!--		<header>
			<a href="http://tutorialzine.com/2012/04/timeline-portfolio/">Download on Tutorialzine</a>
		</header>-->

		<?=$view;?>

    </body>
</html>