

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Timeline Portfolio | Tutorialzine Demo</title>
        
        <!-- The default timeline stylesheet -->
        <link rel="stylesheet" href="/assets/css/timeline.css" />
        <!-- Our customizations to the theme -->
        <link rel="stylesheet" href="/assets/css/styles.css" />
        
        <!-- Google Fonts -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Dancing+Script|Antic+Slab" />
        
        <!--[if lt IE 9]>
          <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    
    <body>

		<header>
			<a href="http://tutorialzine.com/2012/04/timeline-portfolio/">Download on Tutorialzine</a>
		</header>

		<?=$view;?>

    </body>
</html>