<div id="timelinejs">
			<!-- Timeline.js will genereate the markup here -->
		</div>
        
        <!-- JavaScript includes - jQuery, turn.js and our own script.js -->
		<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
		<!--<script src="assets/js/timeline-min.js"></script>-->
		<script src="assets/opt/js/storyjs-embed.js"></script>
		<!--<script src="assets/js/script.js"></script>-->
		<script src="assets/opt/js/script.js"></script>